# docker-compose.yml
version: "3"
services:
  db:
    container_name: db

    image: postgres:10.4
    ports:
      - "35432:5432"

    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - db-network
    restart: always

  db-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "antoine.kour@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "toto"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - db-network

  backend:
    build: .
    depends_on:
      - db
    environment:
      # DATABASE_URL: postgres://admin:password@db:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    command: ["/bin/bash", "./docker-entrypoint.sh"]
    volumes:
      - .:/sportApp-nodejs/
      - /sportApp-nodejs/node_modules


networks: 
  db-network:
    driver: bridge
